fix(agama-lab-frontend): Migrate to new flow designer
GluuFederation/agama-security-key pull request #9
Opened 2024-11-29 10:50 UTC by syntrydy

Pull Request: Migrating to new flow designer

2024-11-29 11:02 UTC, ossdhaval requested changes

2024-11-29 11:02 UTC, ossdhaval commented on README.md
This README has lot of changes. It is now diverging from the template that we loosely follow for all READMEs of the projects in the `Explore` section. Can you kindly share the reason why the sections like `Where To Deploy` have been removed.

2024-11-29 11:04 UTC, syntrydy commented on README.md
@ossdhaval i didn't change the README, looks like that was change by Milton on the agama-lab-franch

2024-11-29 12:30 UTC, kdhttps approved these changes

2024-12-02 08:04 UTC, ossdhaval commented on README.md
@syntrydy let's revert the README to the previous version. Other changes look ok.

2025-01-15 11:55 UTC, ossdhaval approved these changes

2025-01-15 11:57 UTC, merged